require('colorscheme')
require('mappings')
require('plugins')
require('settings')

-- plugin configs
require('conf.alpha')
require('conf.autopairs')
require('conf.bufferline')
require('conf.cmp')
require('conf.colorizer')
require('conf.lsp')
require('conf.lualine')
require('conf.telescope')
require('conf.toggleterm')
require('conf.tree')
require('conf.treesitter')
