require('colorscheme')
require('mappings')
require('plugins')
require('settings')

-- plugin configs
require('autopairs-conf')
require('bufferline-conf')
require('cmp-conf')
require('lsp')
require('lualine-conf')
require('startify-conf')
require('telescope-conf')
require('toggleterm-conf')
require('tree-conf')
require('treesitter-conf')
